### ISSUE TITLE
Support for "fetch first"

### ISSUE THREAD

**Issue by HaakonSonsteby** [jhannes/fluent-jdbc#14]
It would be nice to have support for standard statement "FETCH FIRST x ROWS ONLY": 
according to [SQL:2008](https://en.wikipedia.org/wiki/SQL:2008).  That would make the statement below easier to both read and write:

![image](https://user-images.githubusercontent.com/1081204/90401001-a1f69300-e09d-11ea-811b-2665ab061714.png)

**Comment by jhannes** [comment]
Fixed in 01e6a41ba4e84752929ce8ab7e0c351829d1a657
