### ISSUE TITLE
Suggestion: wrap `whereExpression` in parenthesis

### ISSUE THREAD

**Issue by jonasgheer** [jhannes/fluent-jdbc#18]
Given this code:
```java
public boolean foo(int projectId) {
    return table
        .where("project_id", projectId)
        .whereExpression("entry_id is not null or entry_comment_id is not null")
        .getCount() > 0;
}
```
The `or` in the `whereExpression` can match rows with a different `project_id` than the one given as an argument.

I was expecting the `whereExpression` to get wrapped in parenthesis and not interfere with the call to `where`. 

Thoughts?

**Comment by jhannes** [comment]
Yeah, fluent-jdbc should take care of this. I've committed a fix
