### ISSUE TITLE
Support for left/right joins

### ISSUE THREAD

**Issue by AndreasSM** [jhannes/fluent-jdbc#9]
A lot of situastions requires you to get a result with an optional hit in another table

https://github.com/jhannes/fluent-jdbc/blob/1f570a86d0f9326382b581356658208f477261b2/src/main/java/org/fluentjdbc/DatabaseJoinedQueryBuilder.java#L96

**Comment by jhannes** [comment]
Resolved by aef38a3fcf4142a13ed7f328dbacbf3266dbcc8e
